#Requires -Version 5.1
<#
.SYNOPSIS
  DeepSeek Harness (dsh web) 一键安装器
.DESCRIPTION
  本脚本完成:
    1. Node.js 引导: 本机已有 Node >= 20.19 则复用; 否则从 nodejs.org 官方源下载
       便携版 Node (无需管理员权限), 并做 SHA256 完整性校验。
    2. 安装 DeepSeek Harness CLI: npm 安装官方 @deepseek-ai/dsh 包到
       %LOCALAPPDATA%\DeepSeekHarness\npm (固定版本, 不影响系统 npm 全局目录)。
    3. 生成静默自启脚本与桌面打开脚本 (无窗口启动 "dsh web --no-open")。
    4. 创建桌面快捷方式与开机自启快捷方式。
    5. 启动服务并打开 Web GUI (http://127.0.0.1:3080/ 默认)。
  Uninstall 模式: 停止本安装器启动的服务进程、删除快捷方式与安装目录,
  不删除用户会话数据 (~/.dsh)。
.PARAMETER Workspace
  服务器工作目录 (影响新会话的默认 workspace), 默认用户主目录。
.PARAMETER Port
  Web GUI 端口, 默认 3080。
.PARAMETER Version
  要安装的 @deepseek-ai/dsh 版本, 默认 0.1.5-rc.3。
.PARAMETER NodeVersion
  无可用 Node 时下载的便携版版本, 默认 v22.19.0。
.PARAMETER NoAutostart
  不创建开机自启快捷方式。
.PARAMETER NoDesktopShortcut
  不创建桌面快捷方式。
.PARAMETER NoStart
  安装完成后不启动服务。
.PARAMETER NoOpen
  安装完成后不自动打开 GUI (仅当 -NoStart 未指定时有意义)。
.PARAMETER Uninstall
  卸载模式: 停止本安装器启动的服务并删除相关文件与快捷方式。
.PARAMETER Test
  沙盒测试模式: 所有目录 (安装目录/快捷方式/DSH 数据) 重定向到 %TEMP%,
  端口默认 3093, 不打开浏览器。仅用于开发验证。
.EXAMPLE
  powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://cdn.jsdelivr.net/gh/squirrelmedia/dsh-oneclick@latest/install.ps1 | iex"
#>
[CmdletBinding()]
param(
    [string]$Workspace,
    [int]$Port = 3080,
    [string]$Version = '0.1.5-rc.3',
    [string]$NodeVersion = 'v22.19.0',
    [switch]$NoAutostart,
    [switch]$NoDesktopShortcut,
    [switch]$NoStart,
    [switch]$NoOpen,
    [switch]$Uninstall,
    [switch]$Test
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$script:NodeMin = '20.19.0'
$script:NodeZipUrl = @{
    'x64'   = "https://nodejs.org/dist/$NodeVersion/node-$NodeVersion-win-x64.zip"
    'arm64' = "https://nodejs.org/dist/$NodeVersion/node-$NodeVersion-win-arm64.zip"
}
$script:NodeZipSha = @{
    'x64'   = 'ea3fad0e67a991d8477d8c01344b56e69c676ccb733f065b22436994b1253f86'
    'arm64' = 'e4a7336010d58ff35b53d9dd5869095c56089c70913cf22508cf8183593e56b2'
}
# dsh.ico (DeepSeek Harness 图标, 由官方前端 favicon.svg 生成), base64 注入于构建时
$script:IconBase64 = 'AAABAAcAEBAAAAEAIACXAgAAdgAAABgYAAABACAARAQAAA0DAAAgIAAAAQAgAJYFAABRBwAAMDAAAAEAIAD1CAAA5wwAAEBAAAABACAAIwwAANwVAACAgAAAAQAgAM0ZAAD/IQAAAAAAAAEAIADUIwAAzDsAAIlQTkcNChoKAAAADUlIRFIAAAAQAAAAEAgGAAAAH/P/YQAAAAlwSFlzAAALEwAACxMBAJqcGAAAAklJREFUOI2FUzFrIlEQXjViQINYiFos9tpELBQLK8kPSCPYhIAS0Mom/0CtbEKMkiZV0kRsTIo7EG0CKdKIRISAtQRJYbHg7nvvO2bc9cIdxw08ZnZmvu/NzpvRNE3TALgAuG07A+AWwIeU0qJDtu3L2DluwmgOWNtpv5SyK6VUAKCU4vOHkKNLud+xGjmEED/sJAGAblVEYJqmA7SUUhQj30+HhMWyLGLF19eXORwO1ePjI+7v73F+fo7ZbMasrVYL8/mciJhxtVrdMNgwjBzdOplMVDweV1SQy+UCaTr9fp8JTk5OEIvF8PDwoEqlkqrX61RNjsrvbjYbRCIR4YAPDg74eDweJhkMBnh+fmbb7XaTFuPxmHi7RLC4urpCKpVS5XIZuq7vE4ns6OgIXq8XvV4PuVwOx8fHmE6n3F0p5YIIzEqlguvray6Vqmk0GvD5fExEsXa7vf8lipFYFvUZWyaoVqs4OzvjwHa7ZX13d8eAQCCAp6cnJBIJ/h6NRhyXUu4JFsPhEOFwWK1WKw4ahsG6Vqsx6PDwkHU2m4UQ/JLOgCy4iWSl02lRKBTYO51O0el0mCifzzM4GAzi7e3NKZ9ZuImG/YzL5VLpuq6SySQuLy8ZdHp6yr8SjUbh9/vRbDad25WUcveMmqZpUsobiqzXa/Pi4kKFQiHuPjWyWCzi/f0dr6+veHl52Q8SgN0gkdh7sB9l0zStz89P5fTCGWV7zEkodzfK35eJRloI8fcG/V6qfy7Tfp1N08xIKW+FEB9CiP+u8y9BlL+K7WIbjwAAAABJRU5ErkJggolQTkcNChoKAAAADUlIRFIAAAAYAAAAGAgGAAAA4Hc9+AAAAAlwSFlzAAALEwAACxMBAJqcGAAAA/ZJREFUSImNVjtIpFcUnhnfL1AQQbDSDSRuIeKzES0ELbS08JHZFRQfnYhrNiks7ARBBi0tdFcDo1aO0TVaKAOi2GihCLIqBrUwgQQ2zvyP+4Xvzr1//vmVZA9c7rnnv+d9zj2/z+cBAAEAfoV/C+BHAL8CuANgqkV8RwjxE++ou37yeuV5haeo/RsAywAMJEDgOWhaHMDP5HHLeEm41A7gewB/KmbbZbWwbRtcpAshLAVaEXmCLyrRwoUQ45Lbtm3DMEzDMIRpmuBSgpNdEAJUYNu2NEDRxt0y3WF5wws0SVn+DO7u7nB7e+ucr66ucH19LXHTNG3FS3hLmeFwOOEJEyWE+J0WUfjNzQ0WFhYwOTmJqakpzM3NobW1Ffn5+VheZmoSMDIygp6eHscbbdjDw8Mfp6enMvkShBAfFY9Jgbm5uaBev9+ftKempuL4+NhRMDw8LOnNzc24v7/H/v4+QqGQ2dTURO8+aOtfW5b1NxkmJiYESYFAACkpKVJgqmvxW2FhIdbX16WCmZkZ6PulpaVIT0/nWTQ2NvIzZb72GYbBOsfh4aGZlpbmWEwmLp710p5kZGRIJQx5VVWVpNEg7pmZmdjc3GTSEYvFxn3xeHybh4GBAYsXysrKZKy10EAg4Ah2K8nKysLGxoZMMr1jWHt7e2morBUVxQhD9Bux8vJyMTY25lTH2tqajK1PKdHe1NfXo6+vTyqiJw0NDZJeU1PjLl1dhZ+pwIzH4ygpKZFVoUpOVwXm5+eRk5PjWF5dXY2DgwNMT0/Lsw5rR0dHoq3jbGwHDKlAeYDa2lpHAePLnbC1tYXs7GxHydDQkKTX1dU5oQuFQpL2bysk9PlM05Qh6uzslBV0dnYmv7Bz6UUsFpNnCtA5YCJbWlpQXFwsaXl5ebi4uHD4XI36mVX0idjKyopMcn9/f8I3w3DCpKG9vd3pB3flDA4Oyu/6OeE7pVgiPsuy3hN7enqydMktLS05Qre3txEOhyV+eXmJoqIip1S5V1ZW4vHxUQvWbKbzLrkbLRqNCsaaiePzQNjZ2ZGCgsGgDFc0Gk0q48XFRW/stZYvstG8T0UkEkFBQYFkZgl2dXXJmPNcUVGB3d1d+UaRpkPU3d3t9kBb/9F5i2KxWNJjx0S3tbUlNZjP1WRUen5+jr29PayuruLo6EhbL5NAWXrSuZ/rt8pV+moxYScnJ5idncXo6CjYhAwbaS/NBj2EFN6bNHhc0+ydqgbbPUS8QAW0g4tDybIs3tVa3yUNnBdGZhDAX57JZnGg6AZ0Wes2gjxv/m8ue4d+osu+bui/+k/hbk88vy0/CCF+EUJwNvIvwyBOGoD3Qojv1F3+tjwT/g+i4OuikOXOSAAAAABJRU5ErkJggolQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgGAAAAc3p69AAAAAlwSFlzAAALEwAACxMBAJqcGAAABUhJREFUWIW9V0ssJVkYvt7PYUE82sLOIy0MQUdYWFhYSDzS6YiIsUCQWNoQsfIaY8EG00jESkQEYYH0oruD0DPjHbHwCEGC9E3a1bhV9U3+o85xqvrW1as+yUlVnTr/6/tf59hsFgOABwAv6TsSQAWAIQD/aJp2o2maos8bWgMwDOAPAFESnRfxspLjcgDwpKm/JxFjTdO+4mlosB78n11XJsnM78UB3WoAwQC6AdxLAlQATv1pHq7+PQD4C8BvMu+fEZ4AYIMzJphfsPwHJHQapoymaf9pmpboVgk8C38D4FJn5LQSrKoqnE4nFEUxS2ZTcgnxgM7zjUsl8Ozv1wDOdUaKLITe6UnfkgBXprO9NKU1riXxfi3LtPEIJT8BWKddiqIw4e6EbG1tYWBgAKOjowart7e30djYKFDi68RTJ1+XYsJDtr5bJ3Jy4cSsu7sbtbW1KCsrQ01NDZqampCTkwMvLy8QGf2n8fj4yJ79/f1sfXFx8cmHOmK6Is77+3vs7+93m1H4HYBD36RdX1+jsrJSCDFPDw8P9gwICMDBwQET9P37d/Zsa2tj/3x8fFBVVcUUe3h4wPHxMT5//qwlJCRgcHDQASBFjoG/dXiUy8tLpKenMyaenp7w9vY2TGJMitE/2pOWlobd3V3hnpGREbZOe+nZ0NAgENMNUsh9JJMLfwXgiru3qKiIEfr6+gpLrSb/HxYWhg8fPjAGR0dHCA8PNyhBk6OZmppKKUpbrxwOxyubXl6Z+ycmJgQhMedWu1OECwkNDRVK8DggOhmt4OBgvodHeAUp8F7/cBYUFBi0lSetWSnCBRASS0tLjFlHR4egi4mJQWlpKTY2nmobBbou871NUZQv9HZzc6P6+/sjKysLCwsLmJubQ29vL4qLixEUFCQEmZUgV4WEhIh14kF09fX14lsSzLOBI/DF5nQ6r+ltc3NTI4K6ujqetyKHDw8PUV1dLVAgRbjVFLA7Ozvo7Ow0rHOFSPnz83ORkjzW9OeVjReIlZUVRpCfny82UwrJxWR2dlYEGHdTXFwcysvL8e3bN6YET0H+Pzk5WdQIcwWlCikU2NvbYwRRUVGw2+0GAl6SaaytrSEiIkK4gCwkHxNKNHJzc9m6n58fexJyHFHzYAqoqspS0G63a5GRkYxoZmbGJRG3ZH5+3uAOonn37h0+fvyIvLw8Q3ZQZrng9ewCVVVZEJKhhYWFjKikpERYLg/6pqpGo7m52ZCyrrIiMTERt7e3ruDnjNcNaTg0NCQYkJWmwBGMSJG7uztkZmaKeOAByHOf1oeHh63gf05DSIWIAikpKYkRx8fH4+zszAD9p0+fsL7OGiYby8vLrB/IruDC375968pyMwIVP5Ti6elpAWlGRgZOT08FVWtrK1tvaWmBw0H9BOjr6zP0DXrPzs5mCFkoIPxPsg3NSFEUBk17e7vwZ2xsLCYnJxnF5uYmKzxcCO+EPT09BhSomI2Pj4tsMrmQ++OpGdGg1kjtWFeCadjV1SWQIFjJJTR5j6D16Ohotm91dZVBzpHgbqDSLseOZP1zO4bpQEIBwqOfSjKPiZc6I52CTk5OMDU1xZoRBaDedmU38OD7U8iGiyOZqqriSEa+HhsbY6lJ7ggMDGSBR90vJSWFlW4KRjcBZ4beeCRzdyiV+wE/9VxcXLDAJP/K6cXTkx9caXIj3B5KLY7lFxJkpImldfzEbGW4BPuF5bHc4mLyr/liwg+X8vzZiwnxlGX8qqvZvc4j+KeE256VkC+nFBdDv+xyKinh9noOgA4yZC25SL6e055IGVF31/P/AZrjeEUyFePsAAAAAElFTkSuQmCCiVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAACXBIWXMAAAsTAAALEwEAmpwYAAAIp0lEQVRogcVaWWhWSRZO8sd9RXHHHteOS2sEFdxQRKPihiBqQmxR9EVkGp2IoNEX8UFRMU4cfRBXBH3UJ0XadmsXMCKICu4aFFy7jXGLf+79hq+sUzn35v6biTMFlfpzb9Wp76x1qupmZWVYAOQAiKn/swH0B7AQQDmAMwAeAngPwLP1vX32h+2zCMDPHKvoxEg7UzyZAM+2k5hJAXT3fX8VgCsAvuBb8ZG6SB+OuQqgBECPqDkaE7yTDoBeAHYBqFKAfN/3awHEbWuehUAn61MFYDdpR2m5oeBz2fq+38z3/VJrDgYUgSgwmZao8aS9nnPpuRsMHsAQABV2Etp0/DtBJ2QG32iSNst1ztkgJhT4BQCqLeHGBp6IEZYPAAq/iwkF/jchbFXdqMX3o2URMqvfMmJCnEfAW2JepsA8z3M1EVAvyTu+VkITJmLpgi+KkEQAYLjK89raWlPTZdRPzIDt4pgoSsqECpPDVKRxktfgoiYNg/n06RMePnyI+/fv4+PHj4G+wuDWrVtRXs51DYjHxfTrFYPB87z3NTU1+RqrBm8WDoYvu7iI9N2EGhx/f/jwAW/evMHbt28NWBY+O3HiBBYuXIhevXqhefPmaNmyJc6cOVOPDgH36NEDI0aMCAgoSjCe58kLYmuuMQdMx8Z5Q18NNg8+f/6M48ePY+nSpWbS3r17o0uXLujatSv69++PCRMmoG/fviC57OxsU/l77969AalLe/PmTTRp0sT0Wb9+Pb5+/RrwC9G29K+uro5fu3aN/5cGTEmZTj/f9/9WtucGE3heXp4DxzZRzcnJccBatGiBx48fRzJw4cIF0yc3N9e0ffr0MdrTfbS2Fi1a5JNeZWXlX8TqsCvHZXpg+mvJr1q1ygGPxWJmQoJkFUnzN9+x1YywXb16tQNFmgKuoqLC0RUm+Pv8+fMG+J49e7B48WIUFxdj4MCB5n23bt3EUcrDWvjJ9/23In0Bv2LFCiclAkwm+agq2po9ezZev34dcFb+37lzZ9dPtDZlyhSMHz8+MF7mLigoMCrxPI9Yf9I+UCKOKxLavXu3GUTCqcwmWZXJKcUHDx4Y2mLv8+fPD5iR9h3RNtumTZuaZ9QKlWkF/S/HgO/7l6yajeg5UYcOHQKm0JAq0qXj371710WY69evm0il5xFzDGsmPz9fwrHBSMwi/TwGGateo6Lly5e7icXeG8qISJmR6tGjR46JQ4cO1TO5sE8x3DJqWSFLPCfmPEq/2NqVUc2LFy/QqVOnyIgjDpepP4hpCBMDBgzAkydPHBOMciJpPSdNZ8GCBXj69KkLsWLqti2mBnZa6RvvOnr0qCPUtm1bE+MZQsmUJq5VnQ54bddiTpcvXzaAaFYMkTJmyJAhBgdX8fB6pNcpAGVkwCyT8Xi8VodNTiBORwJcda9evYotW7Zg5MiRAVCpnJx9hFkyLkzk5uZi3bp1KCkpCfjKvHnznMSjUheVJfxOBgxKz7LIkEciQ4cOdSEvTIBdz549i4kTJybUhjDVrl07E/PfvXuH0tJSA1rWlBxr49JXGFu2bJmLVgmSPVHHgyy9ReSfcePGGSLdu3d3sVvSYkqDTGl1HjhwAO3btw+ETA2KudDcuXONSbAcPny4nl/kWEaEgR07dqRK8NwWNEuFJfNkzJgxTqri+SH7q5c237lzB4MGDQqA0HXjxo3o168fbt26Zfoz94kK0dmWaWqXJVVaTlNyDAjI6dOnO4L79+9PJQn3jtFr+PDhkZogc0z8KisrTV/G82HDhgWYEPAMFq9evXKCSoeB91FrAGthYaHTQDJiIqlnz54ZSYelK+COHTvmxuzbty/ArLQzZsxwcybDbtsq58TxeNyM2LVrl5u4Y8eOeP78eToEnSYuXbrkQqJemNi2bt0aGzZswMGDBzF27NhAH2FAtJ7CfATMfRdGJQmSLFEIbt++PQAwHSa2bdsW6Q+Jwm22fd6zZ08Tro2Ik2g8HEbLZH4BwbxDiDNP564rGVExMV0nT54c6Q9kSkeeLMXopk2b0hVW3UImqYTORDdv3uyWcrZr1qxJSVgik5gaI1ibNm2SSj4rlK1WVVWl7bw6lXDJnOd5vkQUJlB6kTp58mQgFdaFav/y5dv5LpmQPmVlZQlDqzCWY+mfPn3ajU9RdDL3cyCdJg9CgKcFenlneLtx44ZjQiTN/gyfgwcPdkzynTDBtEDT0TXHmhHTkzTBG/K2/TNyQ6OPR2bOnGkmaNasmWkZyy9evOgmq6mpMb/nzJnjJLpkyRKTNlh6xn/Ep7QmBPzatWvrCSWp+OscuG5DE95SCgM0JdmPij9wA7Jz585AhsjIpdNspsvcrEi5d++eSQ4FuM5QV65cidu3b6e0e8FmAdZtKdWmvlx7uIBjRsqUWpgQkKNHjzbbznPnzpnoEY4orVq1MouVlJcvX2LSpEmBjDTX9iVdLmCi3SSaqL+pDx2r/KU51Sus5EicVLSRLLKIiYwaNcoweOrUKbP7ohmG/SFmhTJt2rRkDIj0ibFv4IQu0cGWJsaDLebteumnbxCMpMi68n14l8XM9MiRI+bIkdorKSkxPsPTD2agsvNKYE5y2BY82NLHdDy2izpa1Oc5PB2bNWtWSi3oSkaLiooCG6RMil+HJfpoMXRCl6/uv+od7srkdDyaRkFBgUkBaPMESifnVpQr+NSpU00qLWm0PnbnohiPx11azt8pNi/EFH24G3G8XqgGB6gKAF14uEs/4d6WUmY6LAtbsnFpFM4tgwozvSNIeMEhkgzvzsJF+iQ6kk9RMr/giLhi+meqKyZZ+MI3Mt8BuHGumCKYmPd/uuSr5gXjd4GPYOKX//E1awXnbBB4xURM3d6s+9EX3b7vl6qL7tiP+NTgHzbteNfInxr8h7Qb/VODFB97rARwuQEfe1xhVvnDP/YIMRL1uQ3zKO7sUn1uw3f/BvCr/USnwZ/b/BdlSemqbHG+SwAAAABJRU5ErkJggolQTkcNChoKAAAADUlIRFIAAABAAAAAQAgGAAAAqmlx3gAAAAlwSFlzAAALEwAACxMBAJqcGAAAC9VJREFUeJzVW3doVc0SvzExVvxU9NnF7tOHDRURy7OhYANFsID6fWJBLFieJYrdRP8wef4hKgpiQ2NQn4qgWD71WbCg2BXFguXZa4wluTnz+O3d2cw595zbkmv8Bk7OuSd7dmd+M7s7M7vr8xUREVEJIkoiogTxLpGIGhHRCCJaQUR7iegKEf2PiHKIKF9fOfrdFV1mhf7m76hT1Jeg2yjh+1WIAoInit/JRNSdiNIty7pGRLkUO+UR0Q0iytB1JjvALT4gKKCNRNY4EVUjotmaYSdZEMayLL/WuOVRJl+XyfMoc8uyrDlEVN2Nh2LROgUETyWit0IQK4ywkZIERdWrXlrWO91Nqv1UayCNuH5GX5xERC+ZWSF0vEiCgQZfaR7UOBFXayA9AOHZsqxmRPRfh+CF0XS05GzzNBH9QygmIZ4m/wcRfdZcxFvjkVoEaZ7+KPIuQQHhE/SVwQ0Xs+BOkvz8W/OsrkIL7wuYfCkiytQNeI3QxU1qptHPu8CzlCFmzVsB4ffpirmBX5mYx/1EVDomEChg7mz6UvNFSpZlqauoywpeM2UXjgaARH1Pd1RYaMrPz6e8vDx1l+/iQMxzupQpGuHHMH/hWoJmIITf77ddeCf/F4UGTb2gnJwcGjlyJF24cCFawLigmR3CCV9C31sS0Ufmw7XmGIRC2Zs3b9KqVatoxIgR1K1bN2rfvj1NnjzZVShYCmjnzp0EtubOnat+5+ZGHF4o5vx+/8fs7OyWUsaQFkBEf2qG/W5CQHBJ79+/pytXrtChQ4coKyuLdu3aRQcOHKCzZ8/Sq1ev6OnTp7RmzRrq1KkTJSUlKWESEhLUvWzZsrR+/XpTtyQGZfjw4apskyZN6M2bNwacSMD3FzD7Z0gLoALTn+IlPJs06OHDh7Ry5Urq3r07VapUiUqUKKGYlBeELF++vBJSvgMIJUuWVL83b97MjAYBDfrx4wc1b97cfA+ruXfvXhA//A3eye4IysrK8p8/fx6Pk127AhVEdDWI6Jk0H4GkukOjU6ZMoXLlytk0yc8AApd8jysxMVFdeM//K126ND169MimbScA2dnZVLVqVVMH7mXKlKFx48bRy5eBMIQFdrOerVu34hurf//++PkUMkqZndpPc9M+V3706FGqU6eOEdYplFNor/cSuC1btph+7dQmD4DVq1cPahO/W7ZsaUAAff36la5du0ZnzpyhY8eO0fjx442lDR48WAmRn5+/XMrsE9qvpaMrm/ZZeCDJ/Rd3N5OP5mIAKleuTHv37jVtseB8x7u2bduqstwm7qVKlVLPM2fOVOVSU1Opbt26QXwlJyere0pKiqowNzcXiNUyslOB9uc6tc/C79mzx5g1o18Ul7QOdKvv37/bzJfvY8aMMcA7AWzcuDH17NnTtTtKRe3fD8eQlEBIqjitIFmnr1S7svEbN24oLck+WJQXGGTB+vTpQx8+fAjq11CAtAA3SwJvrCRn16tXrx59+vTJyEZEV4moZGAACADQ020Awp3RjYfwUgjuq507d6a3bwPJJQYAU16HDh2CrECOC271cp0rVqxwm2l6SAA4zM2TBTdt2hR34d0Yhr8A34KFB50+fVrNGl6WEApQDI5CsTYX2aczKDAJZSKsffTHVq1aRdRgUV6s4R49etDnz59tnl9mZqYRzG3GgaJkv2/dujU9efLENp44ukGST+fef7D1s/b37dtnKuZ+isZx4Zn7XDxB6N27N3358sU4RKATJ05QzZo1XUGQljRhwgTbeCJ7uL6jwqY+vQBhtB9q5PUyt6KaFqVA0hLY/WUQ2DWWXRPOEsqmpKSogZtN3sNdZkRGGOdH5+2N+Tdq1MhU3rBhQ4XowoULadmyZTR16lSlnWrVqtmEiNUq+Bs2YwaCQQAvcGxA7969oxo1agR1zcOHD9u07XSTHcTjQBoA+I9Gy88f37lzxzgaYObcuXNupqSmFjA2bdq0IA/Ryzy9Lpgta1S60vwOv0ePHq00LK2Gn+GlspWEC5eFr7MXAFxms+D+f/DgQZspXr161VgGBiQ5nTDKGLAQ1cExYSEiGa1xnzNnjtLspUuXlHUBDNklvOqS/48yV8CFLiPh+Zxl4SkHEZpE/8iRI+q9U3AOjaULi+Bl0aJFZsoKNYWyAJinEV3yaL97924V8MgyPNbI+vh/v/32mwJQKiQM8cLKc59emVXEAKxbt87mR2/cuNH2f9caNRisgYsXL1KzZs0iGkgRWSKk7tevH3379k19v2PHjqB+7jV2IKnC7UaZdcoBAMZmWMANGzaoinkcmDFjRlgAnECAoJW+fft6gsDv5s+fr6Y3PN+6dcvUhUAnlBXx9wiNQc6QOAJe/TYARALB1kDXrl1tAkZCXBcGpWHDhrmCwCZcu3ZtZS1InLx48cLU8fHjR5MMcbMEBiYSC/WgfFsXYDNCPC0bQlbn8ePHUQHA9bFFDBo0yFObcsS/fPmyyQOAtm/f7goAfwMrvXv3ro3/KCjHNgiycM+fPzdprMKizExhymzXrp0rCDzA4blXr14cuZkpmcciOe0xIF26dDFlo1AOF3xmmwa5AgiJbAvPz7jD8YmykaDugGwNBjunME6tNm3alBYsWECzZ8+m+vXru5ZnEDMyMmJRTME0SMIRkswinST7LRD3coiiAQGWFGpgi8STZDCqVKmiMs6a/4h5cTpCaW6hMFLbzBAzi1x+rADI74YMGRJyekSbHHi5AcLfTZ8+3QZuFMTmkmoLhjQ66gficXZvZS7u1KlTsTZqAHjw4IEt0RlO417ah/Mk642GFX0fDgCaynBYCoc+yIgzCEhWcFQWzuyczlFRJFtY++np6bEqIigcTpIJEfVHM3z//n2qWLGiQZ6ZnTdvXtQDj4zOuH72DyIFQeYOY/T8ghMibikxiSyEdQ6GuG/bts0VBGYIgxPmfoTQWEzhOmWMjukWoXYkIHC7SHCyTxLjWGRPiYGQIHSWYibhjbVo0cIwyX0QczOCFgbBqV04NAwa8gZwr7leuWx1/PhxE/15zQByHfHkyZOFEd4zKZrsTIuDmEk0CoGdKWcwzoI5V4vx2+n4DBgwgJ49C6y8oSxbz9q1a4MAdgoPMBGmc1geIwDBaXHSiwN6B6bnshhHiMyknB4nTpyowmD9vREMFsLfsDXUqlXLZG9QN4fAS5cuNWWlJTAAsCKsIMl2YthvELwwQmGWxiQIS5YsMdpgK2DBELSAQYSzzNj169dtWVwJXlpawP2QecjFixebss4cIT9j+QvRYwyxCRfE0lhN2wIpFSyPpXotjTMIy5cvD3KQ5AAGBjH4DR061OQMnT48lx84cCDdvn1b1csgYAkLViIdIrYg2Q4SJuwGR9IdhEz2xVGX5fGnblYg43xkjDhYYh8hkhSY1CYLg2gO2VykxVavXq26DQBEvRwEOa8YPFOWxX153GEFk7ysQFoCRvk2bdrYBOL+K5fNQwHhLMMAYtZBYgSxB4IipMGxEQOZH+QmYF1Io71+/dooJ0LtT5KyxrRFRoKA/o5dIrx4KmcH574B54X/8yILgwCzhiVwLsApWCyRqJAh9BYZ5yYpy7I+hNskxaYHhwYDZIMGDaJya/mqUKECjRo1Sg2asm63LXX8/wj3CHHyE7JEvknKF7j/zu2FQNfGHBYhMcXNmjVL9WsMZtAq+jI0jf6OsQMLGx07dqSxY8eqmIB9AxbOS7BCuL2RbZOLdaOk2x4dMAtAYB0Y6aFdpK6Q84OJu2m1iDdMxrZR0mWr7M5IQHBzc8NRFKYcLcmtskYW38/cLG1pT01uXWPzjsWLi4KYx32adwVAVMJ7bJff8RfaLp9Z6O3yTPLgARGt+gscmMgQZl+kp0YS9fPoX/jIzO9xO0VGwYemTv1Ch6ZwgKt53A5NhTg2N7E4j83ptn/OsbkQXeJviLCK4eBk2k8/OBnB0dl/IQ0Qx6OzN/Xx3OI9Ohvm8HRJy7L+qWeMqyLlHgvl6jrgkXb7pQ5P+xzkcXwev/n4PEx2D47I6wVZ7H8zx+f1O6xTogwSM/gGaxZxPT7/fwUdeTrwOiWRAAAAAElFTkSuQmCCiVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAAsTAAALEwEAmpwYAAAZf0lEQVR4nO1dB7QURbPevYsBBFEU5RpABHPELCZMPyr+oM+sPMRjxnTE7DFgQlQw56yoT9HDL5gTgvLzzBmzmB8qZsUrN0y98w39zV/bO7s7Mzs7u3vv1jnDXjbMdFd9XV1dXVWdStUYiUhaRDIi0inP511EZB3Hcf5LRI4XkQki8qCITBeRd0VkruM4vziO85eItOHC33hPRP7PfGe6+c0Ec489cU/cO88zM+ZKl50BHZGM0DuBydb7YHo/EdnbCGuaEWKLxE8t5t54xhUiMlxE1szTpjoYYhJ8g81gx3GWFJHdReQyEXldRBbkEZhjhNbiOE4rLvMeL5u8z9T33d/n+b6Yz94TkStFZIiIdPcBQ0MszOhIZDPOqPVhInKTiHyjBKaF5wq6gIBLJYfgMIJvsz4DzRWR20VkqIgsUQjIdcoveG8eFZF1ReQCEfnEYrQt8EqRY4CgtYT76jjOFyIyTkTWt+2XuvALjHgzWgaJyFQRaVbMbvMZedVGbT5tbDZ9GWz1sQ4EwwjNFKj5l6xRXe1Cz0dtRkNpQt/2ovB1/zsU2apQRHYRkZmKUZxr2wU5C/vSZgFhV9X/jrNqsNQ91tYPFxk10o6B8BjsnA4xLehRDwvZGEh/dwTBFwFCk+FFt3arDay5fiezdu5wgi8ChI9EZGebXzVPatR3FpHxaplU6SVctZBt71xFl3NNTwl035q/NxCR1/LMg3WytKHjOG/Sf1CTU4Ke7x3HOUhEfjedLORWrZN47msxPBtecyAw81favF5CdNdHfSjS/Bpv+OnyNFXNpAy9riLyUI07cqrFqwiarFYJDdVu7DU6jvNv0/C6yo9vSvhfEemleV2Nwu+tlnjl2JPvqNRiXhGs0kfzvJqE319EPrYaXKf4iDzFzmh/zftqmPP7GEeGbmid4ifyFgOtr5ZBJYXfKCLvWA2sUzLTQWNFQMA1qbH2uYtXF35yRF7PUquDZPwEXJOavydZDerw1NbWJi0tLfDmJQWCSbZckjL6EJRZF74iLfQEAKBBcImWTRLC/2/z4Jpy8EAora2t7gjF1dra6o3YUkct7gN69tlnZfTo0fL99997zywnqY0kz21cbuFvLCK/8flS5ZSESnbMvefOnSt9+vQRsOmEE05w3wPIykzsGGQyoCwgUHN+Z8dxXjGdrtp9fAjET+jz5s2TZ555Rq655ho59dRT5aijjpLDDz9cTjrpJLntttvkp59+8n4fhijkMWPGuMJPp9PSu3dv+fPPPyPdLyypXUTIprOWWdxLvgnlEj6YhNGqVbRW07zsz/Eefkv1bo+4jz/+WC6//HLZeeedpXv37q6A7KuhocF9XX311UMLjd/766+/pF+/fln3w3SQkBbQMpmgZRan6kdYc6zzPtUz589SicL47rvv5IYbbpDttttOFl100RyBd+rUSRZZZBH3lZ/37dtXJk6cGHn0T5s2Lev+eIV2AaGPSVDbfxg5WMsuDtXfTTl7SpIWR6rN6AULFsgnn3wiTzzxhNxyyy0ybtw4Oe2001wmjhw5Ug455BD3OuaYY+Sss86S8ePHy3333Scvv/yyq7p//vlnmTJliowYMUKWXnppTxXjNZPJuBf+z/f0SN1ss80iG20U7jnnnOMJn88AyF566SWvf3EB3Y/Mvd1/HMd5Oxb/gBr940pV/RS8rZ4xH++3336y6qqr+o7WYheYvdRSS7mXrdYp9Hy/S6VSstJKK8kXX3wReaQSMHvvvbcHNg0uGIWvvvqqJyROaXES7/fHH39IU1MTmXxxSVpAzfsbqejdSNaMHvGYY++8807Zcccd8wocTMRIyndRfdvCBdP93s/3jFQqJVdeibxOkeZmnYQUjNgn9G/AgAFZgtcg69q1q5x//vny66+/er+Lyy4gaGfMmCE9e/aENnOMNmtasGDBgMj2gFL/U6OOft3R+fPny1VXXSWrrLJKjnqm0GwVHVQDhP0tv9epUyd5552FM1uUUUkANDU1ef3SAOD/+d4KK6wgF154obfaKAUEXOmApk+f7mpA9mvs2LHujZuamqZoWUZR/UP4vLANpNUOevzxx2WttdbymK/n5LAqP45Lz9HvvvtuyQAAuHv16pV1b/t5ur+Ydh5++OGiIODKSK969MoIBJtpySWXdO+72GKLua9nnHGGltkQLdPAI9/8PYPyDMMYdur333+XI444Ikvt2iOkUhengOuuu67kKQBLQAg1HwC0NuBzcV1xxRW+4CtkJ2jQXXDBBZ7Q9b2x7MVtzE+mRxr9psSK274owv/oo49kww03rDrBa2GkUinp37+/u2yMYgRSGADPuuuum3XfYs+msLBy0ULXgsfK5vnnn5e77rpLrr/+endpe/XVV7srIXoccS+Cjq+TJi3co2tubqYW2DO0FhCRF8MCgAycOXOmLL/88m5jghpllQTBTjvtJL/88kuOwRoUAKDtt98+S7ME1UBrrrmmO5pdRhvhQ+j77ruv9OjRo+g9bOHjvTfffJN9oexeCDX6kbnKPkZxiNDjFpQZ1QCCvn37um7isCBgv0eNGuUBPuizyZ877rjDvcfXX38t++yzj+/3eHElZA8q/n/FFVe0vZlOYOeQsvz/ZW7QGoYJr7zyiueEqTaVHwQEDQ0Ncsopp8jff/8d2DCk1oM/Iyzo+V04uN577z3PjohiJPNew4YNy9JOSoaTtYwLrfuRxsXJsOgwIJPmzJnjzUu1MPL9QJAx7R40aJB8++23WQIu1v/333/f82uEXY4uu+yystxyy4XWIH4AABCtdlOGzSrdrKGQ+r+Y4A5jBG2zzTYldaAarnQ67bUf6/q33nqrKAjUSJMtt9zSA1OUZ0fVmgTS4osvLp9++mkWMC1ZjvWdBpTqR97+ZwR3UNWPrVWNwlq/MqYfMMJgkBUDAT+DlR6FD1EcYH7theHoI3wty09V5nHab/SjIqYL6KDCx5ZnVNRX85UxTIWThcZhPhBQC/z222/unkbS/CB44BHMAwAt02E5WkDN/7cR1EFdoH4+8PZyNZg+wZcPb2YhEHBA3H777VkAKvfFKQurhwLC1zK9JQsASv0vZUqharQU7Oyll16aaGcrCYIuXbq4btdCIODA2HXXXbOEU+62NTY2ymeffVYMACzM8S0rmrqyV+p/aBDhs5OwkvFg/LRaHT1xM7pbt26unyMfCMj8b775xvUwlnNw6E2mIPsKlmx397SAAsCEIOqfD9EBEJUWUJIg6NGjh8yaNasoCF577TV3eVcOEGjXOvcyAu4sssHjjcwXVlw3lbjfKmb9c/TDRx1k86O9XRkjSOy7M8jDDwQUBkDAXcI4QMB4B/yNTaBbb701jPC1bN+wjcD+QYI+2Fk8uBzIroUrY/oMwb7xxhtFQQAH2cCBA0saLHZ002qrrSYvvvhilJgCyhay7qcBMNxCSO4vlW98hx126LAASKl+w+/OgBK/7WQKB/GAw4cP94QZRODa50/BY0l65plnusvNCMIXS8YHagBcXmz+59z24YcfenvQheLt8l3tDQSNjY1e4KdfLgKBAYeS5k+YZ62xxhquzfXVV195g7GEuMIWHT5OAEwrtvlDNYewLs0A3ali+/78DpCt97Fr9WowfUU41tSpU32DOci3iy++2Jdv9gV3LlzKBx98sFxyySWuwQkNQgqzU+lHSsbPpZT7dy4/L/BD3+jXfKMD62ZYzNjkwA4htIafwMMEclbj1WCAjOu8887zhG8nqSBHoRDf+D7uwd9rijGaWPsDurBgc3MhAOgwJMx7HM36FQI/+uij3WiU119/3Y2yQUgYQpURDQtHxXPPPedqkCOPPFK22GIL6dy5c1WCIR0hMJUC3Gqrrdz+ayFigwYju9C9+ftrr73W/Q22pBn/F3Nqmd4dXFuHfuV9CpH39ttve8sQHYGCV6g43emirXAcNx7/7rvvlkMPPTQHWJUIGs1YETacqoKCgN+FsBELiS1iEGL/Co1+XOTrRRddlEQ2EWW9BzTACcUMQAoVmTgcqXYHnnrqqawMGObr6Yt5fX4ggbZ44IEHZM899/Q0gx1Nm9Soz1iCCmOvaDtoiSWWkD322COQz4QAQKBn1CDVCHbA8YE8gEQjYtp1Y3WnHnnkkdBLE8a28zdUdcgYOu6447zQMq1iy3kdcMABLpARB4BXjMb111/fA0EYbaDbGyZRBUGfmudlIt78shQrehZaAVBAiEa1AUCmQJWX0nCCgdqD+w0nn3yya1/YoyuuK2MYj2mI7cjiVEuLu8/P2Pswzw+jwUoZSBF4zZtPChT7T6Yg4MBWkXaKVRzIZQ4dn4u5FKq0HNogY+6FsGvdfrRBJ3TCrbvyyiuHBkFQoOAVKyVoPz6/jMQk0udT+vCGYr8aPHhwDgCoDRAVFLfqsoEwefJkbwcyLtsgbe6xzDLLuM6We++913XaINaBbWCfkL3MGgBxglBH9DJEvMxFJSjrd1LFYgB0Q7bddtu8GmD//ff3GBZ7aw0QQFheal9E3AZi2txvnXXW8eLrNQiQ8MIVS1yagDxEwmxC5PkCAIBfgwJg6623zuk4/95000094ZcLvVobYMqh9il1NKaN0KFd4LBBziArhuiMXoLg6aefjhV87AdK1SRUUIIA+CVlTtHO/00lTD9vFpkAi/3HH3/M+U3cpEcjLHWGU0cFQVplCtOnf/rpp3ufP/bYY1lGGZ/NaKg4tADvgbR5/YwEaD40QGCdvcsuu+QFAK4XXnghCQMmazTCaMJI1SMpCgC6du0qX375ZdZ+B64nn3wyxypn/5BSVqoG0pnKs2fPToR/io+tgQDABqGSh1+HyXiTlZoYgvkcpFQxEbUUEAwcONA1ZmEQ4v9I9PATCv+GvwDOHnsgRBn92PHjpk9CRSYXAqDYFKDRf+yxx/oymYBgZGpSHdBt++GHH9z9hVJHZMra30B8n1+f+Nyzzz67pGfaBaWSqChmTwEFjUA90rA96QcAbUTBpZs0CDgiURplgw02iCyQTCbjqmKOSvyfUT+2Wmb/kFVcSi4Af4M6hZrXiRmBQULBicr7778/b0cJgkcffTTrN0kRn/f555/HkpyRMQDi5ozekydRWPhOFNBp+0MHeyS9DFxYI6WALUD0IzjB3ga2VRncxZUAgJ2lTNdt1Lk5bX6HWAbmCGKDhktRbYjCU8mlY5SMXjjYEiavnBwAMD2oKxjzbD7G6rJoiAHQv6sECLCkKlULNJjfwvHDUHA/YxC7mFHAlvAGkCZ2YhoA8GCxzSAKEh3eZJNN8jKW77FESSW0gJ/RWopR2KC2dlG4EjERDHJBaTYEwURZCfgtP5O0/vVmEA4mDJwQgg5rle+HaGzcmAdJJUjnLjJlu9S1elo5jLBMRLhbvukwzOgPkNNX9u3gE4JUA6F6grWaTwPoaB6GRSXcMd8oJh1XUAoIMnkCYaPcN8nt32IBIYFSwslQxPYVim+jZkDcXyWnAf3sKOVbUkW0QSlh7hw8G2+8cU4wTEKUFRK2drGgULuBrAZSSAtgbkMOQSW1gH72brvtFhsIUiVebAPX/gkPEi8o1HGctRgWHigt3I5xz+d25fuwFyqtBQgA7Bkgp6/UqSBV4sVBg7qCjDmoxOj3wsKDJoaEKYika9boPfVKEYF70003VVwLZMyzufOX9OBQMn5WZwYFSg03N3BfhwwZUpCZfH/o0KEVB0C1TAUZ80zEVVSQclPDHMc5KGxhKDo/iqWC4RWhXPq3lQTABx984FXgTCc8FfB5LDxVIX5QxgeETg/XGgBqlRsv+UCgq3Cy7l4lNQEZfuONNyauBTLmWccff3xWWxImyrbJTg/POI7zZlgtgKNdijHSjhmM86AE+ObDAorfZ5RxJgEQcCAgx0CHmFWAcgtEhC0RY3va1ltvvaJTAT8rV8BImBM4CADsGq4Yc3BnIbUPg5j7CRWcCnNLxCgA/NN8GAiaQbaINRPoNStWaSvos2+++WY3UwlxfHqvIohGsO2YTBm1AO+NaUc/u0KUe4iEKhPXPag/wLubYTzO5CvGSAIEhZPoJg4LAjLvwQcf9O4JYMGqZvAmv1dMxfJeo0ePLhsIqskrqmT6jeM4S2ZVC1Va4NYwp4HrrBmd0FkMBEiWhDUeFgR2ZW675gCWpszILZZP71fnOFOGjCMEjiYd65eHyOib/SqFEgB7RD0nIGgFDH6ONCts1IQBAZ+FbVg9vdgZuThzkNm1hbRBm/ISMuMoDnuAfURyCU8jqbQfRMl0qB8AIhWLjjIVaCbjVBFWuwpywHOhY1r5XP4fWUzI4ikGglYDKtQDjhLVY1/8LaqIMaK4wqpfy/KTvGcLRykX73dmQNAESl2ClZnFQcqgkJlMVc+3RYu/Eb3EDZdCBmKrz7K2lC1ebD+zcHM58/xDEGV5UVaBSAsALBi9fpgDI/yOjAl6cIKuqnHiiSd6J3UUGrE6GpcJIX5g09oABZcYrZxvNLb6TGVRQ7yQu6jbqnMbK0C6JMx6WtZ+IOBUMDnKYZFRRpIesZtvvnnWOX75NAJthmJxf/oACPgrGNyZD2CtVhncKCDg97HXP2HCBO9YWsPPctT8KUiBj4yxpoFd+PuwDyQTx44dGwoEFBSMOPyW2sB0IuvQRKpVGFjF4vE0wFDs+Z577vHa2eYDLrZ/zJgxOZokyoUpbq+99nLzGHXwR4JA4EP+kWP8FSIcNWZ+GNp89cuaCTKSdBkWnEOA+XvevHk596fgqK7D3htZuNQiLdbx9dqryBzBKEUpePCTfg9aAWcAwojls8pM7NiMQEKPenqI75MNU8OOJJvZiMvHljIOX4bKh+cRYdRccUQ9GArlbufMmZNzRCuNRQLkoYce8kLho/gJdNwggYoVDMrOJBr6FWb0KzBMj+PgaOTyhx1J9jGr+ZgbVSD4u0ePHu58Xyz/D0EtOOCRv48aD0gtxIHA6agc+QCUmVsGJizFcXi0ebjHROQKYA4OMyVogcFGoBbh32EFYAsjbdqAUq+ofwTjFW5q7NjBztDtx4nfzI4mAMKees7vsejVueeeW86lYrTDo31WBA9H1QIkMhHMRRp0mCmhnFeDj5bBe9AMaCdyCuBQwisyj9l2HAPv539ghe98lwYKgma5KonbS6hk9S8ty7AAoF9ggAkgcO9dKghw2ARiA/TorobSsJ2KaBW2kf4K7GqitBxq99ODGOSCjwTGIE8iK4MhqIM+NtSyLGUqGGsaW5I3Q9cAhEHHQgx+FnMlwZA2DiqAgsLFNDFx4sQcoWGjB9XDkOCB41uw8kE09IgRI+TAAw+Uww47zD2OFisKfAeGZzlzAZSM/A+JjDgNdEUmKeVYYgM9BiAlGgcpcHQFMfySuBqsEzqwW8jdS67f7WrgYXlQps0hL+sXMtMyLAUE1AL/0A8plbQjBO5jfayKNrAqKfiePXu61btppfs5byhM1kGms4rLSS4p9ftlpLZITp8Q9sCEOKYCr7VqgwbMwfFnCO6wCzeXCwxppeq1gYZ1P0rUzp278BiFBAQXe7h35Hm/yFSwuIi8FCcIbAZjRM2cOdPdwLHDt7WlrQ9qyLcMsz/nCLfLwKfNb3HWH/wCiBeslO8+CilZvJx3uzcGEHAqGIDaMnx2nB2xmY2aPzAWsf7m8WtBDLig6/JMJuOmaI0aNcoNKWOqVg2N+qx6P8rqj0f1FwDBgeahZdnj9GM+ijJgjx07bCNHjnTX5ggoQbRtIX8CrHiEqwFAG220kQwbNswtBAmf/OzZs8t5NEsipDx+B5VV+D4guNS0oWx1TXQJeZvwHgorYyWBmEQYkihQhcObpkyZ4u6+IdoI28tISsF3CwWEtNaAqvch8n5cIsI3D0krm+B+qyFlI3vDppT70Cp3TLGnGiXyfJItl0RAoGIIX0wKBJr0UTRchvld9vE17YRazOvM2Nb7JSwNG1F33mpYncpH5DFCpxq1LBInBYLeSLy1Glin+Im8RbjzKhUVvo9R2A8h9lZD6xQftajQ7v6a9xUnBYKV1TH0dRDER+QlptremudVQwoEvVQ8IRrebiyvCpBjGXy9NK+rjpRN0EVE/sc0HB2oHc9K9VCbXuphxaV5XLWEBnJNCgeFQnIdBMGpTfHrMsPXdNULn2QayylhX3UmQX1KKEyOcq//xjo+4GXi6/yYQbAesshND9HBujbIpTYlfBRQWLdmha9JgaAz1JmKWkFn6waiZI16EOroLK55V/Nk7AIaiDvq00rLtaNYC+Rka0M40na0+dVuyJoSljCBpk0dEQiOErw5tGus8unXtsovRqaD1AZrInZd8aZdA8HJtX+mqrm+od2o/DDaQAWczsjmVfuxEZxcwc9i4GaHGPUBbYO0SUWbpQVfw6uGNlubOY7zb1OHKdNu5/oYpgUAYZCITFHnGLj8qwGvYpuPr6PZ9GWw6mPHUfdhyFaFIrK6iJxndsBEMdYFQxVME45pgxY6gzS/MPWW1s439dWpMBA81Wh8CKhkeqPjOAtPWMwWvA2IcoDCsQSuNRGfh0SC20Vkd+8whvqIL0kj5KhKEemGsv/mtDMUPf67gMBaCAwLHH4AcbSQlaALua+bjdfuMtOm7oWAXKfoQHBVpw8YAJA+IrK3yVp6zhyFUo5YhBZz72eNt264iKxmC5jt7JBWfRKkwJBb6+4/W9FrG2v7OKMpJqFSBgIqIESTRDFf7brNx3tGwPgOvostWPwW98C9cE9PrVvP7FSrQv9/lNkH4LJI2vgAAAAASUVORK5CYIKJUE5HDQoaCgAAAA1JSERSAAABAAAAAQAIBgAAAFxyqGYAAAAJcEhZcwAACxMAAAsTAQCanBgAACAASURBVHic7Z0L1E5l2sefeKUXiZyPHRxCJDEjCRUVCh3IMYlCUkJEGk0zqzGmr2+WZVmtpq9kjNWYvsYYq2+WMY2cQo4RJdFQOaSUSIn6f+u/22+9Xs/zvs/hvvd1772v31rXaqZ4nr3vfV/Xs+/7vq7/lUgooQZAPoBmAG4CMBTARABPAXgBwEIAKwG8A2CXb4d9O4afOFbo3xf8ue0AVgD4G4DnAfzO/2x+R3f/O/Ol719RIg+AMgCaAxgA4DcA/gxgDYADkIfXsBrAS/619fevtYz0uClKWH/ROwB4GMAfAWwCcALh44R/7X/074X3pG8MilIYADUA9ADwSwBLAHyN6HISwHoAMwAMBlBfZ4MSKwDkAbgawG99Z/ge8Yb7Dc/6QbCs9PNRFOMAqAvgPgB/L7L5ppzOUX/TcSSAOjoVldACoKr/msvX+u/U0zPmO/8EYwyA2tLPU1HSdfr7ASxTpzceDJb6b1FVdCoqTgGgtb+OPa6/9Nb5BsBfAHQBcJb0s1diCoCaAB4BsFOdXoyd/ulJPen5oMQEAK0A/AnAt+r4zsBnMRfA5dLzQ4ko/tHdIj22c56V/pGiLg8UI2f2dwPYJj2rlYzZCuAuPkP1AyUjAJQC0AfADnW80PMBgOEASqsbKMXC10b/9XGz9KxVjLPdz8sopW6gnAGArgDeUseLPCxQukFdQPEA0Mg/V1bixRJqGqgbxBQAlfyCHCaWKPE9PpwB4Dzp+agEu86/F8Ah6dmnOMNB/7RHjw6jDIAGAP4lPdsUZ1kO4BLpearYOc9nVZmW4iolcdxPLz5bHTE6hTp6rKdkykYAV0jPXyW3ZJ4xIdXTU9yRMPulJhGFDGrN+TX5imKCNwBcLD2vlTTwU3ipb68oJjkCYJA6oaMAKO+X6SqKTV4EUE56viuFANAQwBad90pAvMUjZXVCB/DbVOkrvyKxJLhFev7HPaOPklyquKtI8b2fTq4VhgLrfWrsK4oL/I1zMlAniCsAavkddRTFJTazAYy0f0QaAJcC+I/0k1aUFHwEoKW0n0QSAJ0BfJFq5BXFEb6kuIy0v0QKAANUhlsJEScA9JX2m0jg1+7rTr8SNk4BGCbtP6EGwCh1fiXkx4QPSftRKPHP+BUlCjwu7U+hAsCvpZ+YohjmCWm/CgUAppgeeUVxhMnS/uU0AB6QfkKKYpnx0n7mJACGaONNJSYbg/dK+5uL5/x61KfE6Yiwr7TfOQGAa1S3T4lpU5IuiTjD1kwAPpd+EooiqCnQIhHjqj4t7FHizgcAaiTiBDXVAKyRHnlFcYT1sdET8PX6VcxDUU5nQSyUhQD8qsiNK4ryA79IRBkAN+txn5Ip3377LbZs2YJvvol8J/fvKHKbiCIAGumOv5IpH3/8MS699FJwClWuXBmLFy+O+iAejpzkuC/iuVV6ZJXwceONN3rOX2BVq1bF0aNHEYO+A+USUUE79ijZsGTJktOcv8Cef/75OAzoC4kowH5q0iOp/ATX0R988AE2bdqE1atX47XXXsP69evxzjvv4NixY04NVfv27ZMGgK5duyIm9EuEGQD1tGuPHNu2bcPs2bMxevRodOjQAbVq1UrqUIXtwgsvxLBhw7B8+XLBKwdWrFiR8hrLli3rXLCyBLNkL0iE+Lx/qa2RUc7kiy++wNy5czFgwADUrFmzRGcvyYYPH47vv2fxWvDwHoq7tgULeGweC5YDKJ0IGwAekx65OHD48GHvV/6mm27C2WefnbPTF7V9+/YFfk/c5OOvfHHXNXToUMSISYkwAaC1ynjbg6+/c+bM8XbI8/LyjDs9rXr16nj22WchwcKFC0u8vnPPPTcuy4CCysFWiTAAIA/ABu+yFaOsWrXKW59XqFDBitMX2AMPPCDqXCNGjEjrOmfOnImYtR4rk3AdAI8iBhw/fhx79+7Fxo0bveOqVMad9vfee897Vc8GvoJPmzYNl1xyiVWnp/G124W1df369dO6XuYEfP55rKrJJyRcBkBj+gYikoH26quv4ve//723i969e3e0atUK9erVQ35+flYOVqpUKVSrVg1NmjRB586dMWrUKO9XjNlte/bs+fG7d+3ahWeeeQbXXnut93dsOz6N98SAJc3OnTszuu477rhDbKNSAPpWw4SLADgLwGsIaa45X6/5S9utWzdv/RuE0xW1cuXKGdm9z8a4p+AC6az/i9q4ceMQI5bS1xKOtvAKDZ999pk36Xv37u1tKEk4nSvWt29fuML06dOzuoc+ffrgyBEK7ESHI0eO4NQpygeewd0JlwBQCcAhOM6JEyfw8ssvo2fPnihTpoy447lg55xzDvbv3w9X4CZntvfSoEEDLFu2DFFw/O7du3v3VKNGjWRvZwcBnJdwBQC/h8N89NFHmDJlitirvcs2cOBAuETHjh1zvicGeGZBhjWZ62c/+9kZ9zR//vyif/R3CRcA0MTVM39upvEXRX/t3V/7F9CyZUsjge2ss87CLbfc4p3ChOmXv23btknv5/LLL0/WgryxCwHg/+AYfKWl45cuXVr8F9Z1e+ONN+ASjRs3Nn6PN9xwA9asWeP8L3+7du1S3gPnchJBlIXSzt8Fjq3xn3zySeuJMlEynn64BI9Zbd3rkCFDss7HsMknn3ziHTGXdP2HDiXdZrtR8tiP2UlOwOqxpk2bijtU2GzevHlwCSb32LxfHrOuXLkSrvDhhx96eSHpXHsKIZQNIseCAO6AA3z99dde6qq0I4XVuFRyiXRKlnM17gm5sPexePFib5c/nWuuVIkHbSm5NWjnLw1gO4TZunUrmjdvLu5EYbby5cs79VrcrFmzQO6bm4TzhN5++Ks/aNCgjK43ySZgYd4OVFIcwJ0Qhg8v25RctdPHYMyYMXCFq6++OrDnk5eX5y0dg9rkYw4KE5ayqeDkiUYJ9A3y1/9dCMHMqPHjx6sTG/41dCWBpkePHoE+2wsuuMBzzmzYvXu3dz4/YcIET8CEtRtXXHHFGWZiWTN27NiSLmcHK3GDCAB3Q3C9f9ttt6nzW3CE888/39MFlIY79S6/AW3btg2TJ09Go0aNAr3GWbNmpXN5g4LY+RdJsWKUpq5d0JMjTlanTh3xNwEWZAV932XLlvXW5cXBpUJBeq6ErV27Np3h22L1RADATRCANd9t2rQRd5C4LAcmTpzo5VRIwBJsifueOHFiyrJwFktJPhMGqAyexw02A8C/ETDcoeY6Stox4mZMyX37bW4uB1+3IfX289137Mz1Ey+99JITlaJXXnllJkO42JbztwQQqPLCV199VWx6pJr9Xx4KogQtuFGlShWRZ7vSTxCiPgRFYEJ8SnO5jQAQ6KHpyZMnPaVb6cFXS3jqRQcPsgI1GKSe+7Rp0zypN8m1fjLLQqZtjmnnrxl0xR816aUHXu2nMahbty7WrVsXyLOnGrHE2F933XXo1KmTc4laDEoZwg2D6iYDwGQECHXypAde7cwxYN+BIPryUQhVxz/xo+ahqICof/S3EwGxdOlSLeN1PAA98sgj1vcFkolixNHmnykEki47jBwJAuiMgOA6U0oUUy2zMWDmm82jwmy1AaNk+fn5ubZC72giAPwZAcAjmOuvv1580NXSHwOmvtoS4qRoK1WS4/w87r///lyHcW6uzl+FHaURAE8//bT4gKtlPgbM0aCz2oAOENdnUqpUKbz//vu5DuHXACrnEgBGIwDeffddT51WetDVshsDlqqmUKvJCRbbBNUYJeGY9e/f39QwDs8lACwLorqPmU7SA66W2xhcdtllnrSVafr16xfLZ7Np0yZTQ/ivbJ2/Fv0TlmGmmfRgq5kZA4p5mO4xwNTguGk89uvXz+QQ0odrZBMArKtEHDhwABUrVhQfcDVzY8AmpnRak8TpR6JChQrGxw/AqGwCgHW52DvvvFN8wNXMj0HDhg29KjqTaeFcYsThWT3zzDOwwOuZOn9dnszBIqxvlh5sNXtjQIVmk3sCXBNHXQLuxhtvtJVgRV+unUkAGAXLMO9aesDV7I5BixYtjB4RUlMvqs+sXr16VjZRszoNAPB3m1fCPvTSA64WzBgwpddkslAU9SDLlSuHDRso72+Vv6br/GcDyCn/sCRS9T9Ti+YYUOmX2g6mjo27desmfk8JQ0aF4H/84x8IgC/p2+Ltvl5//XXxQVcLfgy6dOniibqagJ8ThSCQl5eXS7FPNlyTTgB42uYVuCa2oBbcGLBJZ5IGl1nBQqRbb7011KXVCzIX+siV6ekEAGuqv5RUlh54Ndkx6NWrlye5ZQJ+Duvlw/ZMa9eujTfffBMCbCnJ+WvY/Hbt4Sc/+Vyw22+/3TvbNwGPzdgROiw1Ax06dPAET4T4vlilIAC32/pmrtsqV64s/gDUohcECvaW0m20KbXenzp1qreJKUyv4gLAf9v61rlz54o/BDW3xoCZoEWluHOBKbQuFpZdc8013vLXEX5XXABIq/1INqjYh/xEdNGGDh1qNAjwTdOVY+amTZt6vQWCllUvgVWpnD/fVxM1zqeffppVR1S1+FS/mZQXk1IVTvjGugVmLZoMbAbhMcw5yQJAR1vfSCVZ6Umm5n4e/LFjx4zMtyeeeCLw669SpYqnYLRmzRqEgPbJAsDDtr5Nz/7lHSwMxvU7W8HlShD7AKVLl/a+h52Cmdpu6mgzIMYlCwBzbXwTEz+iXsWlZm4MGjRogM2bN2c933jExganJp9JxYoVvR8xyqHPmTPHO8M39bYixIvJAsBbNr7ptddeUwfRIJHRHKA+5OzZs7Oab6ynN30te/fuRcTYUNT5y9jaAGTUtOEATPyoVKnSj6bKQtF7E7n33nszbovFvQST19CqVStEEG4E5hUOAC1sfdNVV12VU3daNqZkCSh3dpnsQaXYL774IuUR0K5du7BixQrvVW3s2LHeGSwDhPRkVst+ScA1djqw7Jg59qYVjyNKs8IBYKCNb+DGSDbrf+ZKz5s3z+g664MPPsArr7yCX/ziF15OgsqQhy9pqCTpcZ652whAEaVv4QDwGxvfQJGDbH712SfANny1ZB32Qw895CVsSE9wtfSO2thAJpW2gI3CoGrVqiGi/Np6+69sEjKYIy4BN3qee+457+0gLIUlcbXq1avjqaeeOu0N8fPPP/daaZv+rvx85sdFknnWU4AffPDBjAf84YetpSNklFM+bdo0fTNw3KpWreptMnNpxzJjG99x9tkUyIokP6UEszGvjW+gCkymA84sLpfgmS8zvLSSMZ5Wrlw5RJR9Bc5f3q8TNk6dOnUyHnBu0rkIXzfZoKJu3brikzIoO/fcc708/ZkzZ2LRokV49dVXMWPGDIwcORKtW7cWv74grH79+ogo9PlzGAAutfHpLO7IJiNr1CjriuQ53xdrG9gBR3py2rQRI0aUmJbLI1mKcdSsWVP8em1Z27ZtEWEuYQDobuOTOTmyGfC+ffsiDLDSi2tPtseWnqQ2EnAygbvy3DOxsQknbYMHD0aE6coAcI+NT16+fHlWA85d+DDBWm8mHdWqVUt8spowLtuyLc1955130Lx5c/F7MGnTp09HhLmbAWCSjU+m3HE2A85f1DBy9OhRrzKMeQzSkzYX4256rvkVffr0Eb8PU7Zo0SJEmAkMAE/Z+ORsRRm4yRZmuPS57bbbxCdutsbxz7WJB5dHPDmRvhcTtnv3bkSY3zIAvGDjk/nqlM2Ac+PQlHa8JIsXLw7tiUHHjh3x1lu5F4c+9thj4veS6xHg927JeZnmOQaAhTY+edKkSVkP/I4dOxAFmJ02cOBA8YmcrV188cXenkzv3r29BC0u6zJ9O5BQ5zFlbdq0QcT5KwPAKhufzBz7bAc+oF5pgUF9OOaxS09oU7kBfLvLRN46rEFgcLRPAMhya52ARo8enfXAM/Ekauzfvz9S0mg9e/bMSAaLCUXS15ypzZgxAxFnKwPALhufzGyxbAeebw9RhdVsUSk2YrJQunDpQLVc6WvOxNaEQ+AzF95jAPjQxicPHz4864G/7rrrEGW4QRiG2oL27dt7G3kDBgxIKuvOQLZ9+/a075tiLWG470QigTJlyhjrZuwwe6wVAuXSB5CTJOq8//77aNasmfhET2VcwhXeAWcn22R/jmW5mcD9nTC8AbVu3RoxYD8DQHJ9rRzhrnEuD4AKPlHnyy+/tFbGmqvxBKMoyQqAMlkGFMCEKen7K8lGjhyJGHCYASAz1cU0mTJlSk4PgHn2cYC/sq45BEUwknW16dat2xl/duLEiRnfM/M8XH77SSQSWasSh4yvGABOuZQIVGAMIHGCm4PSk76wLV269Iz2bsnEVbPdKV+7dq3TS4F3A5Clc4BT1gIA5bVyeQBU840bHDNXnIJZjFyvM7d/06ZNKdWdc3lTmzBhgvh9JlKI0saEU9aWAKk2jdI1FtVkqgkfBahsG6ZGquvXr8/6Xvl8L7zwQvF7SCRRII4JX1nbBMy2HLiwsatQHGEFWlhky3PdrOUbhPQ9JOK5/v9xE/CgLZXdXB9E3PYBCsPgF4YgYKJa7oYbbhC/j0Qh27NnD2LCfmuJQNxFzrVLS7t27RBnqMHn+nJg9erVOd8ni7/YbVf6XhLRbgSSMhHISiowady4cU4Pg5OCu89xhnsCrmwMJrNZs2YZuU8W3kjfSyIEmpQ2UoGtFAOlOjfO1GK0Hgus461JY4GTCSgnJn0viUTCS9OOEV4x0Epbn25CFaZHjx62Li9UjBs3Ttw5khnfTrZu3WrkHnn0K3kv5513XkYVjhFgGQPA31xObuFGGPX24g73VFxNG77yyiuTZg5mCsVVJe+jX79+iBmvMAA8b+vTFy5caOTBUFBD+aE5ScuWLcUdPpWUeK7yWZs3bxa9h5deeilu0+wPDADTbVa8mXgwt956q61LDB0c04oVK4o7fDIbOnQoTp48KZY8lmvi2ZEjRxAzfsMAkHk1R5rwF8HEZGVt9ieffGLrMkOHi8kzBUYNwWSVhCXBLkRNmjQRu+4+ffoghoxnABhm8xs6depk5AGxL5/yE2PHjhV39uLqCNLV06foBk96mH8vec2Loq3/n4oh1lqDmRAHLWwtWrSweZmhg7vVTJSSdvaSnhkD95YtW07bJOSrNguNhg0b5sRypnr16jktXcLeGqyZzW/gBp6pB7Vu3Tqblxo6mG4dFrVhHheynLhq1ari11LUxowZg5jiNQfNt9UenBw8eNDYgxoyZIitywwt/CXNpguz2k9jYKIJSmjbgxNbBUEFmGqlzdqCffv22bzUUOJqklAYrEOHDogpH3vO7wcAq/rHuSgEFzWq1CpnbqS5LrHlqs2fPz+u02lV4QDw57AcW1ExmAkxyuls3LjROy6VdqgwWe3ateOW+luYPxUOAE/aVr81OTlZHKNEpwWXlD35pNVp7zq/KhwA+tv+tmuvvdbYg6tfvz5OnDhh+5JDB4+yfv7zn4s7Vlh6HB4+fBgxpk/hANDc9rdRPdbkA9S3gNRltWFQEpK2Rx99FDGnSeEAkEe5dpvf9vHHHxs9rqpTp04cWjdlBZNvpB3MZStfvnzchWa+BlD6xwDgB4FNtr+VRy4mH2QMurdmBbPuTI91lCybZiYRY/1pzu8HgDm2v5XyUSYfZI0aNVQroBidPV0KJBf9iPmvP3khWQB4GJb57LPPvLJLk0Fg0qRJti87tLBxp/SvrWuWaTPTiDIuWQAIJCWKqismHyiPF/lrpyRfCqTq6BNHYxMS9iVUcFWyAFDW9kYgWbJkifEHS/FRJTnbtm3LWZ49KhZDxZ9kfPNjDUCSIJC7yHsaIiGNGjUy/nBjWs+dFkx4kXY+aevSpYv0Y3CFFUmd3w8A/xXEFZjeDKRddNFFuiFYTIJQ69atxZ1QyrgZSik1xeO3xQWAQMT3vvrqK5x//vlWhCmV5MQ5QSjmKb9F6VFcAKiOgJg8ebKVh61LAbsy7WGzK664Is4FP8k0AKqlDAB+EHgbAXDo0CFUqFDB+AOvVq0aDhw4EMQthPJUQLr5RpDGzU9TTUsiwuZind8PAIEdlE6YMMHKg1cZ8dSwnTcLYaSdMwhTIdkzmJZOAOiMgKDUd7ly5aw8fE34SM3zzz8v7py2jUfDJroVRYxO6QSAs1nCH9QVUeHHxgRg4RHbayvJ4VuStJPaMpaLc4mpnAa7npQpMQD4QWAhAoJ9/2rWrGllIlA9yMXjn1xbaJmA+yTcL5F2VtPGVPMNGzZID6+LvJKW8/sB4L4gr+y5556zNiGaN2/uTH7A8ePHcdddd3nlqNygoljq+PHjsWaNVUnGlLAVdtQUhbm8UZJybyYBoA43jREQp06dQqtWraxmgbmgIFScZBeVfKidGPS6derUqeJOa8rYaERJCidVrbQDgB8EViBA1q5da/XX6Pbbb/cCjSTpFOZQ3Zda/0HBgNO5c2dx583VmOmoAjEp+XdGzu8HgAcQMPfdd5/1XwjJ9TeXI5nsYm/fvj2Q62Lzllq1aok7cS69CKk4paRkZDYBoCbfzhEg7Cpru0kkm2hIkWkSTl5eHh555BFv78A2y5cvR+nSpcWdOVNjMllMO/ukC324esYBwA8CSxEwNsqFixrfNCTOiLPt4HPxxRd742Kb6dOnizt0pv0GFy4M7MAqrPwzK+eXOA0oYMSIEdYnz+DBgwPvCJtrgxQWO7Gzri24POrZs6e4Y6drrCpVSmRYLgGgiq8gGig8tmvYsKH1CXTLLbcEqhDDBim5VuRR1WbFihVWx/6yyy4Td+6SbOzYsdbGIEJw7Vg56wDgBwERGZVNmzYZ1w9MZmxYQq3CoLjjjjuMvPqymtJWlduePXs8wVVpJ09lvXr10jTf9JiTk/P7AeA6CMHmH0FMqAYNGnjSWUHwxhtvGC11ZZ2/DZic5KJ+AI/7qCehpEUHEwHgLADvQYj+/fsHMrFYIReUloDJc/f8/Hwvk9IG3GBz6WSgXr162h4+faiUe1bOAcAPAmLa2zwC4y9dEBOMiUhUj7GdK/D2228bd6yBAwdaSXl2pXKQAVpr+zPiYSPO7weAGgDEZFX27dtnPT+g6L6A7cSSBx980Ph1N27c2MqZ+LRp08QDAAMmO/qouk9anMj67L+YIDAXgqxevdp73Q1qwrFSzmY5MZOeqlSpYvy6uW63sSSwVbadqfGEgi3h9u/fb/weI8Rso87vB4DLfE0xMbgm5Q54kBPugQcesLbpZDPxhksC09c9ZcoU8QBQ+I3gpptuwssvv+xEoZdjtDQeAPwgYD8drQSeffbZwCebrUy8nTt3Wv+1NK2HwLba0s5f1KgwPXr0aG9vRcE/rDi/HwC6xrnRBWv5TeYM8Lzd9jVXqlTJ+FLG5UYjPGHhaU6M5cA6WwsAfhDYDAeQWpNWr17dy08wUaATlCPxdOPxxx836hQ8HXDpiLCoMZN05syZccsZeMvY0V8xAeAuOIItVeF0XzuZjsqMxWyYN2+eV+0X5DV3797d23w0uSfjYrJQYatataonxBJktqcgA6w6vx8ASgN4F47gwsYUf214rMdXbSodp4KCJJTh6tq1q9i1Mutx48aNRoVcwqAlQBm2MWPGeMuuCCf+lLYeAPwgMBAO4VoZKx2Ctf+srONuPFuiUw3IFT1+6hFSM9/UkuCjjz4KTe9BvnXdf//9UTw56BOI8/sBoJS/3nAGrsuDPiIMu7Vp08ZYZSH3REwUOgVl3EOKEGx/VCqwAOAHgd5wDK5Jg0wWiorx7YRjl+sbAVOomTUY9N5Gtr0DIkSvQJ2/UJFQdjtgFuGaNIp690EYU4m5p7Ju3bqc6iFYSci9Bun7Kc74tvi9A/0ZDLDe+s6/C23EMmH37t2hELVw2Vh7wbwHpt0uW7YsYyUiip/w77t8fxHhehHnLxQE/g4HOXbsGPr06SM+0aJkzIG49NJLcf3112PQoEGeRBmNJyCjRo3CPffcg969e3uKxqzgrFOnjvg1pzKeCMSq24/FANAAQHC6WlmsSV1OWImLNWrUyJMzk76OAhnxCPQOPAGgUcIFgmwpng3c6eZDl554cTUW7XAJwTyIBQsWiDYiYW+GiNQM/CbhCgDOBeB0feann36Km2++WdwZ4mas4U92usBy3tmzZ6Nv375WyqKLGveEnn766UBFYC1yAEDFhEsAuBuOwyUBqwnZTELaMaJuFStWxPz589N+Nnv37vVaojGpi5uHHTt29DIsM001pphpu3btcOedd+Kpp57yqjgj8LpflDsTruEfC4qXC6fDf/7zH0/1R9pJomrMCjRZhsy3ty1btmDVqlWeQ7O/AoML/8n/v379euzYsSOQDkoO8G+xY7+SAHARN+ARAvg2QOUcFvVIO0xUjGfrbHcekddsF2FpY4OEywB4BCHi8OHDnuqPzc7EcTCKprz++uvSjzPqjE+4DoA8PzspVDB77eqrrxZ3pLBZmTJlAmtgGnM20bcSYQDAFZIqwrnAY6omTZqIO1YYjAlB777rTGV4lDlhTefPFpSPQ0jhefXcuXPRtGlTcSdz0Vq0aBFYExXFY2IibPglw9yxDC08v6bqbFhq3W0b34yoZBRjvT0JlgUm9GEaAHUBREKLiUdNzH8PQ6mraWvVqhXmzJnjvRkpgUL9tvqJMOOibkCuXYqYrBL15QEltFjcw9JgRYy+iSgA4EVEkDfffNOrKrvgggvEHdaE8e2GwqH8tWc5ryLKHxJRAcA5ADYgwlBoc+rUqWjbtm2oqg+Zbjty5Egvq445EYozR375iSgB4AJmdSIGsPKNElsPPfQQ2rdv74xMGa+DOoDDhg3zsiCZEq04B/fMLkpEEaqX8JQNMePkyZPYvHmzV/3GpJlevXp59fFly5Y17uQsnrnkkkvQpUsXDBkyxGsIwrx5ntfrJp7zfMfuW4koA+Bx6VF2CfYRYEtvnqsz92DWrFmeiAnLaAuMDUjuu+8+739Ts4//nbLeXKvz77FzMoth9BU+i6iNoAAAA3pJREFU9ExORB0/P+Bv0iOtKI7xv85W+ZmGGxwAVkuPuKI4As9ayyfiBIBqAMz2rlaU8LEbQI1EHAHQlBW50k9AUQR3/Jsk4gyATq6qCiuKRVgt21na/5yAKY9xPB5UYssppshL+51TALjLPwdVlCjzPYB7pP3NSQDcL/10FMUyY6X9zGk4QLafgKIIMUnav0IBgCd0iioR45fSfhUqwqYurCjFMFXan0IJgJG6MaiEfMNvjLQfhRoAA1lQJ/0kFSWLo767pf0nSnkClEZWlDDwjZ7zmw8C7QFErsujEjkOA7jG9PxXfggCDQG8J/2EFaWYwp545/bbBkBVACtTPQFFEWJtbKv6ggZAOQB/1amuOCTmkS/tF7GC6il+roAWESmSx3y/pcqVtD/EFgDXAjioPqAEzKcAbpSe/8oPQaAe+3SoCygBsTGy0t0h1xl8QV1Ascwf2OhGer4rKQBwe1QakipO8QWA/up44VkSLJWeMUpk+Dc7XUvPayXzU4IxmkKs5MBJlvHqLn+IAdAq6o1JFWta/S2l569iAAB5/tvAUXUWpQSO+/klpdX5IgaAiwH8U11AScHrABpLz1PF/t7A3QAOqBsoPvsBDFbHixHsxeZv8HxdMAuUWDbnmAGgovR8VGRLjP8iPROVwFkEoIE6nlIQCLroaUFsdvev02mvFBcImOutRIu3AfThHpBOfSWdjcIeAN6SnrVKzmznBp8e6ykZw0kDYJAGglCyCcAAzeJTjADgan/jiCIQirus9N/e9FVfMQ+AywDM0RoDp6Bk/IsAWuicVwIBQGUAwwFslZ79MWaHn7ZbXae9IgaA1gCeBXBM2iNi0nTjL/5pjb7mK06+FfxLxUqNQuHXJQDuAVBJ+jkrSokAqOIfP3HjUHsbZs53/oYeqzhr6pRTQguA2v6bAXsZfGn2xzFSHAHwCoB7AdSSfm6KYhwAZXwp8+maX+Cx2dfWv4Zjo1NOiRWsRPM3tH7pr3OjXJ3IpdB6vwKPabnVpMdfUZyCktN+0tE4/2x7g7/zHTa+9q99tn8v7O5cVnp8FSWskmZNAfQF8GsA8wCsArBP2sv9a+C1/AnArwDc4V9rnvS4KUpc3hiaAOjmKx097K+p/wfAAgDL/WSlXb4d8nvYF9ZHPOr/u0OF/txW/+8u8D9rmv/ZQwB09b9TG2Qkws3/A+czAyuukcC5AAAAAElFTkSuQmCC'

function Write-Step([string]$text) {
    Write-Host "==> $text" -ForegroundColor Cyan
}
function Write-Ok([string]$text) {
    Write-Host "    [OK] $text" -ForegroundColor Green
}
function Write-WarnMsg([string]$text) {
    Write-Host "    [!] $text" -ForegroundColor Yellow
}
function Write-Fail([string]$text) {
    Write-Host "    [XX] $text" -ForegroundColor Red
}

# 快速 TCP 端口探测 (500ms 超时)
function Test-PortOpen([int]$port) {
    try {
        $client = New-Object System.Net.Sockets.TcpClient
        $async = $client.BeginConnect('127.0.0.1', $port, $null, $null)
        $ok = $async.AsyncWaitHandle.WaitOne(500)
        if ($ok -and $client.Connected) { $client.Close(); return $true }
        $client.Close(); return $false
    } catch { return $false }
}

function Get-NodeVersionOf([string]$exe) {
    try {
        $raw = (& $exe --version 2>$null | Out-String).Trim()
        if ($raw -match '^v?(\d+\.\d+\.\d+)') {
            return [version]$Matches[1]
        }
    } catch { }
    return $null
}

function Get-DshInstalledVersion([string]$exe, [string]$bin) {
    if (-not (Test-Path $bin)) { return $null }
    try {
        $raw = (& $exe $bin --version 2>$null | Out-String).Trim()
        if ($raw) { return $raw }
    } catch { }
    return $null
}

# ---------------- Uninstall 分支 ----------------
if ($Uninstall) {
    if ($Test) { throw 'Uninstall 与 Test 不能同时使用' }
    Write-Step '开始卸载 DeepSeek Harness 一键安装'
    $helperDir = Join-Path $env:LOCALAPPDATA 'DeepSeekHarness'
    $dshBin = Join-Path $helperDir 'npm\node_modules\@deepseek-ai\dsh\lib\bin.js'
    Write-Step '停止本安装器启动的服务进程'
    $killed = 0
    try {
        Get-CimInstance Win32_Process -Filter "Name = 'node.exe'" -ErrorAction SilentlyContinue |
            Where-Object { $_.CommandLine -and $_.CommandLine.IndexOf($dshBin, [StringComparison]::OrdinalIgnoreCase) -ge 0 } |
            ForEach-Object {
                try { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue; $killed++ } catch { }
            }
    } catch { }
    Write-Ok "已停止 $killed 个进程"
    Write-Step '删除快捷方式'
    $desktopLnk = Join-Path ([Environment]::GetFolderPath('Desktop')) 'DeepSeek Harness.lnk'
    $startupLnk = Join-Path ([Environment]::GetFolderPath('Startup')) 'DeepSeek Harness.lnk'
    foreach ($lnk in @($desktopLnk, $startupLnk)) {
        if (Test-Path $lnk) { Remove-Item $lnk -Force; Write-Ok "删除 $lnk" }
    }
    Write-Step '删除安装目录'
    if (Test-Path $helperDir) { Remove-Item $helperDir -Recurse -Force; Write-Ok "删除 $helperDir" }
    Write-Host ''
    Write-Host '卸载完成。会话数据目录 (用户主目录下 .dsh) 已保留, 如不再需要可手动删除。'
    return
}

# ---------------- 根目录确定 ----------------
$isTest = [bool]$Test
if ($isTest) {
    $helperDir = Join-Path $env:TEMP 'dsh-oneclick-test'
    $desktopDir = Join-Path $helperDir 'Desktop'
    $startupDir = Join-Path $helperDir 'Startup'
    $dshHome = Join-Path $helperDir 'home'
    if ($Port -eq 3080) { $Port = 3093 }
} else {
    $helperDir = Join-Path $env:LOCALAPPDATA 'DeepSeekHarness'
    $desktopDir = [Environment]::GetFolderPath('Desktop')
    $startupDir = [Environment]::GetFolderPath('Startup')
    $dshHome = Join-Path $env:USERPROFILE '.dsh'
}

if (-not $Workspace) {
    $Workspace = if ($isTest) { Join-Path $helperDir 'workspace' } else { $env:USERPROFILE }
}
if (-not (Test-Path $Workspace)) {
    New-Item -ItemType Directory -Path $Workspace -Force | Out-Null
    Write-WarnMsg "工作目录不存在, 已创建: $Workspace"
}
New-Item -ItemType Directory -Path $helperDir -Force | Out-Null
$logDir = Join-Path $helperDir 'logs'
New-Item -ItemType Directory -Path $logDir -Force | Out-Null

Write-Host ''
Write-Host 'DeepSeek Harness 一键安装器' -ForegroundColor White
Write-Host "  模式:            $(if ($isTest) { '沙盒测试 (TEMP)' } else { '正式安装' })"
Write-Host "  安装目录:        $helperDir"
Write-Host "  工作目录:        $Workspace"
Write-Host "  GUI 端口:        $Port"
Write-Host "  DSH 版本:        $Version"
Write-Host "  自启/桌面快捷:   $(if ($NoAutostart) { '跳过' } else { '创建' })/$(if ($NoDesktopShortcut) { '跳过' } else { '创建' })"
Write-Host ''

# ---------------- 1. Node.js 引导 ----------------
Write-Step '检查 Node.js'
$nodeExe = $null
$systemNode = Get-Command node -ErrorAction SilentlyContinue
if ($systemNode) {
    $nodeVer = Get-NodeVersionOf $systemNode.Source
    if ($nodeVer -and $nodeVer -ge [version]$script:NodeMin) {
        $nodeExe = $systemNode.Source
        Write-Ok "复用本机 Node $nodeVer ($nodeExe)"
    } else {
        Write-WarnMsg "本机 Node 版本过低或不可用, 改用便携版 $NodeVersion"
    }
}
if (-not $nodeExe) {
    $arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'x64' }
    $nodeRoot = Join-Path $helperDir 'node'
    $nodeExe = Join-Path $nodeRoot "node-$NodeVersion-win-$arch\node.exe"
    if (-not (Test-Path $nodeExe)) {
        $zipUrl = $script:NodeZipUrl[$arch]
        $zipPath = Join-Path $helperDir "node-$NodeVersion-win-$arch.zip"
        Write-Step "下载便携版 Node $NodeVersion ($arch, 约 35MB)"
        try {
            Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing -TimeoutSec 600
        } catch {
            Write-Fail "下载失败: $($_.Exception.Message)"
            Write-Host '请检查网络后重试, 或先自行安装 Node.js 20.19+ 再运行本脚本。'
            exit 1
        }
        Write-Step '校验 SHA256'
        $actual = (Get-FileHash -Path $zipPath -Algorithm SHA256).Hash.ToLower()
        $expect = $script:NodeZipSha[$arch]
        if ($actual -ne $expect) {
            Write-Fail "SHA256 不匹配! 期望 $expect 实际 $actual"
            Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
            exit 1
        }
        Write-Ok '校验通过'
        Write-Step '解压便携版 Node'
        New-Item -ItemType Directory -Path $nodeRoot -Force | Out-Null
        $tar = Join-Path $env:SystemRoot 'System32\tar.exe'
        if (Test-Path $tar) {
            & $tar -xf $zipPath -C $nodeRoot
            if ($LASTEXITCODE -ne 0) { throw "tar 解压失败 (exit $LASTEXITCODE)" }
        } else {
            Expand-Archive -Path $zipPath -DestinationPath $nodeRoot -Force
        }
        Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
        Write-Ok "解压完成"
    }
    $portableVer = Get-NodeVersionOf $nodeExe
    if (-not $portableVer) { throw '便携版 Node 校验失败 (node.exe 无法运行)' }
    Write-Ok "便携版 Node $portableVer ($nodeExe)"
}
$npmCli = Join-Path (Split-Path -Parent $nodeExe) 'node_modules\npm\bin\npm-cli.js'
if (-not (Test-Path $npmCli)) { throw "未找到 npm: $npmCli" }

# ---------------- 2. 安装 DSH CLI ----------------
$npmDir = Join-Path $helperDir 'npm'
$dshBin = Join-Path $npmDir 'node_modules\@deepseek-ai\dsh\lib\bin.js'
$installedVer = Get-DshInstalledVersion $nodeExe $dshBin
if ($installedVer -eq $Version) {
    Write-Step 'DSH CLI 已安装'
    Write-Ok "@deepseek-ai/dsh@$installedVer 已就绪, 跳过 npm 安装"
} else {
    if ($installedVer) { Write-Step "已装版本 $installedVer, 升级到 $Version" }
    else { Write-Step "npm 安装 @deepseek-ai/dsh@$Version" }
    New-Item -ItemType Directory -Path $npmDir -Force | Out-Null
    '{}' | Set-Content -Path (Join-Path $npmDir 'package.json') -Encoding ascii
    & $nodeExe $npmCli install --prefix $npmDir --no-save --no-audit --no-fund "@deepseek-ai/dsh@$Version"
    if ($LASTEXITCODE -ne 0) {
        Write-Fail "npm 安装失败 (exit $LASTEXITCODE), 请检查网络或 npm registry 配置"
        exit 1
    }
    if (-not (Test-Path $dshBin)) { throw "安装后未找到 $dshBin" }
    Write-Ok "安装完成: @deepseek-ai/dsh@$Version"
}

# ---------------- 3. 图标 ----------------
Write-Step '写入图标'
$iconPath = Join-Path $helperDir 'dsh.ico'
try {
    [IO.File]::WriteAllBytes($iconPath, [Convert]::FromBase64String($script:IconBase64))
    Write-Ok "写入 $iconPath"
} catch {
    Write-WarnMsg "图标写入失败 ($($_.Exception.Message)), 快捷方式将使用默认图标"
    $iconPath = $null
}

# ---------------- 4. 生成 VBS 启动脚本 ----------------
Write-Step '生成启动脚本'
$autostartLog = Join-Path $logDir 'dsh-autostart.log'
$launcherLog = Join-Path $logDir 'dsh-launcher.log'
$serverLog = Join-Path $logDir 'dsh-server.log'

$silentVbs = @'
' DeepSeek Harness silent autostart (generated by the dsh-oneclick installer).
' Starts the Web GUI server hidden (no console window, no browser popup).
' Skips starting when a server is already listening on the GUI port.
Option Explicit

Const NODE_EXE   = "__NODE_EXE__"
Const DSH_BIN    = "__DSH_BIN__"
Const WORK_DIR   = "__WORK_DIR__"
Const GUI_PORT   = __GUI_PORT__
Const LOG_FILE   = "__AUTOSTART_LOG__"
Const SERVER_LOG = "__SERVER_LOG__"

Dim fso, shell, guiPort

Set fso   = CreateObject("Scripting.FileSystemObject")
Set shell = CreateObject("WScript.Shell")

guiPort = GUI_PORT

EnsureDir fso.GetParentFolderName(LOG_FILE)

If IsPortListening(guiPort) Then
    WriteLog "server already running on port " & guiPort & " - nothing to do"
    WScript.Quit 0
End If

' Let the logon desktop settle before a heavy server process starts.
WScript.Sleep 3000

If IsPortListening(guiPort) Then
    WriteLog "server appeared while waiting - nothing to do"
    WScript.Quit 0
End If

shell.CurrentDirectory = WORK_DIR
WriteLog "starting dsh web (silent, --no-open) ..."
On Error Resume Next
shell.Run "cmd /c " & Q(Q(NODE_EXE) & " " & Q(DSH_BIN) & " web --no-open --port " & guiPort & " >> " & Q(SERVER_LOG) & " 2>&1"), 0, False
If Err.Number <> 0 Then
    WriteLog "error: could not launch the server: " & Err.Description
    Err.Clear
End If
On Error GoTo 0

Dim i
For i = 1 To 60
    WScript.Sleep 1000
    If IsPortListening(guiPort) Then Exit For
Next
If IsPortListening(guiPort) Then
    WriteLog "started: server listening on port " & guiPort & " after " & i & "s"
Else
    WriteLog "warning: port " & guiPort & " not listening after 60s (see dsh-server.log)"
End If

Sub EnsureDir(path)
    On Error Resume Next
    If Not fso.FolderExists(path) Then fso.CreateFolder(path)
    Err.Clear
    On Error GoTo 0
End Sub

Sub WriteLog(message)
    Dim f
    On Error Resume Next
    Set f = fso.OpenTextFile(LOG_FILE, 8, True)
    If Err.Number = 0 Then
        f.WriteLine "[" & Now & "] " & message
        f.Close
    End If
    Err.Clear
    On Error GoTo 0
End Sub

Function Q(text)
    Q = Chr(34) & text & Chr(34)
End Function

' Listening probe over loopback HTTP: any HTTP response (200/303/401) proves the
' port is served. No temp file and no child process, so concurrent scripts cannot
' race on a shared file and boot-time polling stays cheap.
Function IsPortListening(portNumber)
    Dim http
    IsPortListening = False
    On Error Resume Next
    Set http = CreateObject("WinHttp.WinHttpRequest.5.1")
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    http.SetProxy 1, "", ""
    Err.Clear
    http.SetTimeouts 700, 700, 700, 700
    http.Open "GET", "http://127.0.0.1:" & portNumber & "/", False
    If Err.Number = 0 Then
        http.Send
        If Err.Number = 0 Then IsPortListening = True
    End If
    Err.Clear
    On Error GoTo 0
End Function
'@

$openVbs = @'
' DeepSeek Harness desktop launcher (generated by the dsh-oneclick installer).
' Opens the Web GUI in the default browser. When the server is not running,
' starts it silently first, waits for the port, then opens the authenticated
' URL printed by the server into the shared log. Falls back to the plain URL
' (works when the browser already holds the 30-day session cookie).
Option Explicit

Const NODE_EXE   = "__NODE_EXE__"
Const DSH_BIN    = "__DSH_BIN__"
Const WORK_DIR   = "__WORK_DIR__"
Const GUI_PORT   = __GUI_PORT__
Const LOG_FILE   = "__LAUNCHER_LOG__"
Const SERVER_LOG = "__SERVER_LOG__"

Dim fso, shell, guiPort, checkOnly, idx

Set fso   = CreateObject("Scripting.FileSystemObject")
Set shell = CreateObject("WScript.Shell")

guiPort = GUI_PORT
checkOnly = False
For idx = 0 To WScript.Arguments.Count - 1
    If WScript.Arguments(idx) = "/check" Then checkOnly = True
    If WScript.Arguments(idx) = "/port" Then
        If idx + 1 < WScript.Arguments.Count Then guiPort = CInt(WScript.Arguments(idx + 1))
    End If
Next

EnsureDir fso.GetParentFolderName(LOG_FILE)

Dim startedByUs, settle, i
startedByUs = False

' The autostart entry may be mid-boot: give it a moment before starting our own.
If Not IsPortListening(guiPort) Then
    For settle = 1 To 10
        WScript.Sleep 1000
        If IsPortListening(guiPort) Then Exit For
    Next
End If

If Not IsPortListening(guiPort) Then
    startedByUs = True
    WriteLog "server not running on port " & guiPort & " - starting it silently"
    shell.CurrentDirectory = WORK_DIR
    On Error Resume Next
    shell.Run "cmd /c " & Q(Q(NODE_EXE) & " " & Q(DSH_BIN) & " web --no-open --port " & guiPort & " >> " & Q(SERVER_LOG) & " 2>&1"), 0, False
    If Err.Number <> 0 Then
        WriteLog "error: could not launch the server: " & Err.Description
        Err.Clear
    End If
    On Error GoTo 0
    For i = 1 To 120
        WScript.Sleep 500
        If IsPortListening(guiPort) Then Exit For
    Next
    If Not IsPortListening(guiPort) Then
        WriteLog "error: server did not start listening within 60s"
        If Not checkOnly Then MsgBox "DeepSeek Harness could not be started within 60s." & vbCrLf & "Log: " & LOG_FILE, vbExclamation, "DeepSeek Harness"
        WScript.Quit 1
    End If
    WriteLog "server listening on port " & guiPort
End If

' The token URL is printed by the server once the tree finishes booting.
Dim tokenUrl
If startedByUs Then
    tokenUrl = WaitForTokenUrl(30)
Else
    tokenUrl = WaitForTokenUrl(3)
End If

Dim target
If tokenUrl <> "" Then
    If TokenUrlValid(tokenUrl) Then
        target = tokenUrl
        WriteLog "using validated token URL"
    Else
        target = ""
        WriteLog "log token URL stale - falling back to plain URL"
    End If
End If
If target = "" Then
    target = "http://127.0.0.1:" & guiPort & "/"
    WriteLog "opening plain URL (browser cookie path)"
End If

If checkOnly Then
    WriteLog "check: would open " & target
    WScript.Quit 0
End If

shell.Run target
WriteLog "opened " & target

Function WaitForTokenUrl(seconds)
    Dim waited, url
    For waited = 1 To seconds * 2
        url = LastTokenUrl()
        If url <> "" Then
            WaitForTokenUrl = url
            Exit Function
        End If
        WScript.Sleep 500
    Next
    WaitForTokenUrl = ""
End Function

Function LastTokenUrl()
    Dim f, line, pos, prefix, c, ch
    LastTokenUrl = ""
    prefix = "http://127.0.0.1:" & guiPort & "/?token="
    If Not fso.FileExists(SERVER_LOG) Then Exit Function
    Set f = fso.OpenTextFile(SERVER_LOG, 1)
    Do Until f.AtEndOfStream
        line = f.ReadLine
        pos = InStr(line, prefix)
        If pos > 0 Then
            LastTokenUrl = ""
            For c = pos To Len(line)
                ch = Mid(line, c, 1)
                If ch = " " Or ch = vbTab Then Exit For
                LastTokenUrl = LastTokenUrl & ch
            Next
        End If
    Loop
    f.Close
End Function

Function TokenUrlValid(url)
    Dim http
    TokenUrlValid = False
    On Error Resume Next
    Set http = CreateObject("WinHttp.WinHttpRequest.5.1")
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    http.Option(6) = False
    http.Open "GET", url, False
    http.Send
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0
    TokenUrlValid = (http.Status = 303)
End Function

Sub EnsureDir(path)
    On Error Resume Next
    If Not fso.FolderExists(path) Then fso.CreateFolder(path)
    Err.Clear
    On Error GoTo 0
End Sub

Sub WriteLog(message)
    Dim f
    On Error Resume Next
    Set f = fso.OpenTextFile(LOG_FILE, 8, True)
    If Err.Number = 0 Then
        f.WriteLine "[" & Now & "] " & message
        f.Close
    End If
    Err.Clear
    On Error GoTo 0
End Sub

Function Q(text)
    Q = Chr(34) & text & Chr(34)
End Function

' Listening probe over loopback HTTP: any HTTP response (200/303/401) proves the
' port is served. No temp file and no child process, so concurrent scripts cannot
' race on a shared file and boot-time polling stays cheap.
Function IsPortListening(portNumber)
    Dim http
    IsPortListening = False
    On Error Resume Next
    Set http = CreateObject("WinHttp.WinHttpRequest.5.1")
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    http.SetProxy 1, "", ""
    Err.Clear
    http.SetTimeouts 700, 700, 700, 700
    http.Open "GET", "http://127.0.0.1:" & portNumber & "/", False
    If Err.Number = 0 Then
        http.Send
        If Err.Number = 0 Then IsPortListening = True
    End If
    Err.Clear
    On Error GoTo 0
End Function
'@

$silentVbsPath = Join-Path $helperDir 'dsh-silent-start.vbs'
$openVbsPath = Join-Path $helperDir 'dsh-open.vbs'
$replacements = @{
    '__NODE_EXE__'      = $nodeExe
    '__DSH_BIN__'       = $dshBin
    '__WORK_DIR__'      = $Workspace
    '__GUI_PORT__'      = [string]$Port
    '__AUTOSTART_LOG__' = $autostartLog
    '__LAUNCHER_LOG__'  = $launcherLog
    '__SERVER_LOG__'    = $serverLog
}
foreach ($key in $replacements.Keys) {
    $silentVbs = $silentVbs.Replace($key, $replacements[$key])
    $openVbs = $openVbs.Replace($key, $replacements[$key])
}
[IO.File]::WriteAllText($silentVbsPath, $silentVbs, [Text.Encoding]::ASCII)
[IO.File]::WriteAllText($openVbsPath, $openVbs, [Text.Encoding]::ASCII)
Write-Ok "写入 $silentVbsPath"
Write-Ok "写入 $openVbsPath"

# ---------------- 5. 快捷方式 ----------------
function New-DshShortcut([string]$lnkPath, [string]$vbsPath, [string]$description) {
    $ws = New-Object -ComObject WScript.Shell
    $shortcut = $ws.CreateShortcut($lnkPath)
    $shortcut.TargetPath = Join-Path $env:SystemRoot 'System32\wscript.exe'
    $shortcut.Arguments = '"' + $vbsPath + '"'
    $shortcut.WorkingDirectory = $Workspace
    if ($iconPath) { $shortcut.IconLocation = "$iconPath,0" }
    $shortcut.Description = $description
    $shortcut.Save()
}
if (-not $NoDesktopShortcut) {
    Write-Step '创建桌面快捷方式'
    New-Item -ItemType Directory -Path $desktopDir -Force | Out-Null
    New-DshShortcut (Join-Path $desktopDir 'DeepSeek Harness.lnk') $openVbsPath 'DeepSeek Harness Web GUI'
    Write-Ok (Join-Path $desktopDir 'DeepSeek Harness.lnk')
}
if (-not $NoAutostart) {
    Write-Step '创建开机自启快捷方式'
    New-Item -ItemType Directory -Path $startupDir -Force | Out-Null
    New-DshShortcut (Join-Path $startupDir 'DeepSeek Harness.lnk') $silentVbsPath 'DeepSeek Harness silent autostart'
    Write-Ok (Join-Path $startupDir 'DeepSeek Harness.lnk')
}

# ---------------- 6. 启动服务 ----------------
if (-not $NoStart) {
    Write-Step '启动 DeepSeek Harness 服务'
    if ($isTest) {
        $env:DSH_HOME = $dshHome
    }
    Start-Process -FilePath (Join-Path $env:SystemRoot 'System32\cscript.exe') -ArgumentList @('//nologo', $silentVbsPath) -WindowStyle Hidden | Out-Null
    $up = $false
    for ($i = 0; $i -lt 90; $i++) {
        Start-Sleep -Seconds 1
        if (Test-PortOpen $Port) { $up = $true; break }
    }
    if ($up) {
        Write-Ok "服务已启动并监听端口 $Port"
        # 等待 token URL 出现在服务器日志 (boot 完成标志)
        $tokenUrl = $null
        for ($i = 0; $i -lt 60; $i++) {
            Start-Sleep -Seconds 1
            if (Test-Path $serverLog) {
                $line = Get-Content $serverLog | Where-Object { $_ -match ('http://127.0.0.1:' + $Port + '/\?token=') } | Select-Object -Last 1
                if ($line) { $tokenUrl = ($line -replace '^.*(http://[^\s]+).*$', '$1'); break }
            }
        }
        if ($tokenUrl) {
            Write-Ok "认证地址已就绪"
            if ($isTest) {
                try {
                    $resp = Invoke-WebRequest -Uri $tokenUrl -UseBasicParsing -MaximumRedirection 5 -TimeoutSec 15
                    if ($resp.StatusCode -eq 200) { Write-Ok "token URL 验证通过 (HTTP 200)" }
                    else { Write-Fail "token URL 返回 $($resp.StatusCode)" }
                } catch {
                    Write-Fail "token URL 验证失败: $($_.Exception.Message)"
                }
                Write-Step '验证打开脚本 (check 模式)'
                & (Join-Path $env:SystemRoot 'System32\cscript.exe') //nologo $openVbsPath /check /port $Port | Out-Null
                Get-Content $launcherLog -Tail 3 | ForEach-Object { Write-Host "    $_" }
            }
        } else {
            Write-WarnMsg '60s 内未见 token URL 输出 (服务可能仍在初始化)'
        }
        if (-not $isTest -and -not $NoOpen) {
            Write-Step '打开 Web GUI'
            Start-Process -FilePath (Join-Path $env:SystemRoot 'System32\wscript.exe') -ArgumentList $openVbsPath | Out-Null
            if ($tokenUrl) { Write-Host "    如浏览器未自动打开, 请访问: $tokenUrl" }
        }
    } else {
        Write-Fail "90s 内端口 $Port 未就绪, 请查看日志: $autostartLog / $serverLog"
    }
} else {
    Write-WarnMsg '已跳过启动 (-NoStart)。之后可双击桌面快捷方式打开。'
}

# ---------------- 汇总 ----------------
Write-Host ''
Write-Host '安装完成。' -ForegroundColor Green
if (-not $isTest) {
    Write-Host "  打开 GUI:  双击桌面 DeepSeek Harness 快捷方式 (或访问 http://127.0.0.1:$Port/ )"
    Write-Host "  开机自启:  已注册于启动文件夹 (删除其中 DeepSeek Harness.lnk 即取消)"
    Write-Host "  卸载:      powershell -NoProfile -ExecutionPolicy Bypass -Command `"& ([scriptblock]::Create((irm 'https://cdn.jsdelivr.net/gh/squirrelmedia/dsh-oneclick@latest/install.ps1'))) -Uninstall`""
}
